apiVersion: v1
kind: Pod
metadata:
  name: build-img
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: [
      "--context=git://192.168.0.35/garmas/continuous-delivery.git",
      "--dockerfile=Dockerfile",
      "--destination=garmas2022/delivery",
      #"--no-push"
    ]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /root
    env:
      - name: DOCKER_CONFIG
        value: /root/.docker/
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: docker-hub
      items:
      - key: .dockerconfigjson
        path: .docker/config.json
