---
apiVersion: v1
kind: Pod
metadata:
  name: delivery 
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args: ["--context=git://gitgarmas.ddns.net/garmas/continuous-delivery",
           "--dockerfile=Dockerfile",
           "--destination=garmas2022/cautiva"]
#    volumeMounts:
#      - name: kaniko-secret
#        mountPath: /root
#    env:
#      - name: DOCKER_CONFIG
#        value: /root/.docker/      
#  restartPolicy: Never
#  volumes:
#    - name: kaniko-secret
#      secret:
#        secretName: docker-hub 
#        items:
#          - key: .dockerconfigjson
#            path: .docker/config.json
    volumeMounts:
      - name: kaniko-secret
        mountPath: /root
      - name: dockerfile-storage
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockercred 
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim
